apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-portfolio-deployment
  labels:
    app: react-portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-portfolio
  template:
    metadata:
      labels:
        app: react-portfolio
    spec:
      containers:
      - name: react-portfolio
        image: ajaysinghb/my-react-app:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - managed-nodes
